services:
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: [ "postgres", "-c", "max_connections=1000" ]
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=postgres
      - POSTGRES_DB=evolution_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    networks:
      - evolution-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=EMAIL
      - PGADMIN_DEFAULT_PASSWORD=PASSWORD
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    depends_on:
      - postgres

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    networks:
      - evolution-net
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: unless-stopped
    networks:
      - evolution-net
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  postgres_data:
  pgadmin_data:
  evolution_redis:
  evolution_instances:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
