# Generated by Django 5.2.17 on 2026-08-19 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0002_baba_jogador_baba'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='hora_fim',
            field=models.TimeField(blank=True, default=datetime.time(23, 30), null=True),
        ),
        migrations.AddField(
            model_name='baba',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(19, 0), null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='estrelas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='presenca',
            field=models.IntegerField(default=0),
        ),
    ]
