# Generated by Django 5.2.17 on 2026-08-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0003_baba_hora_fim_baba_hora_inicio_jogador_estrelas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='numero',
        ),
        migrations.AddField(
            model_name='jogador',
            name='id_whatsapp',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
