# Generated by Django 5.2.17 on 2026-08-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0004_alter_jogador_options_remove_jogador_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='estrelas',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
