# Generated by Django 5.2.17 on 2026-08-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0005_alter_jogador_estrelas_alter_jogador_id_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='local',
            field=models.CharField(default='Luis Viana', max_length=50),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='estrelas',
            field=models.FloatField(default=1),
        ),
    ]
