# Generated by Django 5.2.17 on 2026-08-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0006_baba_local_alter_jogador_estrelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='descrição',
            field=models.CharField(default='Baba na quadra do Luis Viana das 7 as 11 e 30', max_length=200),
        ),
    ]
