# Generated by Django 5.2.17 on 2026-08-20 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0007_baba_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='dia',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 20, 3, 5, 52, 693674, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
