# Generated by Django 5.2.17 on 2026-08-20 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0008_baba_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='is_goleiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baba',
            name='dia',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 20, 3, 20, 28, 542463, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
