# Generated by Django 5.2.17 on 2026-08-20 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0009_jogador_is_goleiro_alter_baba_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baba',
            name='dia',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 8, 20, 3, 44, 44, 540597, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
