# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0010_alter_baba_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='jogara',
            field=models.CharField(default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='baba',
            name='dia',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
