# Generated by Django 5.2.17 on 2026-08-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0011_jogador_jogara_jogador_posicao_alter_baba_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='is_goleiro',
        ),
    ]
