# Generated by Django 5.2.17 on 2026-08-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0012_remove_jogador_is_goleiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='presenca',
        ),
        migrations.AddField(
            model_name='baba',
            name='limite_gol',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='baba',
            name='limite_linha',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='jogador',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
