# Generated by Django 5.2.17 on 2026-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0013_remove_jogador_presenca_baba_limite_gol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
