# Generated by Django 5.2.17 on 2026-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0014_baba_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='jogos',
            field=models.IntegerField(default=0),
        ),
    ]
