# Generated by Django 5.2.17 on 2026-09-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0015_jogador_jogos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_baba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baba', to='webhook_handler.baba')),
                ('fk_jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='webhook_handler.jogador')),
            ],
        ),
    ]
