# Generated by Django 5.2.17 on 2026-09-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0016_listadeespera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadeespera',
            name='fk_jogador',
        ),
        migrations.AddField(
            model_name='jogador',
            name='lista_de_espera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores_na_espera', to='webhook_handler.listadeespera'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='baba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores', to='webhook_handler.baba'),
        ),
    ]
