# Generated by Django 5.2.17 on 2026-10-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0017_remove_listadeespera_fk_jogador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidado_por', to='webhook_handler.jogador')),
            ],
        ),
    ]
